# Generated by Django 3.2.7 on 2021-09-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Приветствие')),
                ('content', models.TextField(verbose_name='Описание')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('contacts', models.TextField(verbose_name='Контакты')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_race', models.CharField(max_length=50, verbose_name='Порода')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Пол')),
                ('name_of_dog', models.CharField(max_length=50, verbose_name='Кличка')),
                ('tattoo_number_microchip', models.CharField(max_length=50, verbose_name='Номер чипа')),
                ('studbook_and_registration', models.CharField(max_length=50, verbose_name='Номер регистрации')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('father_of_dog', models.CharField(max_length=50, verbose_name='Отец')),
                ('mother_of_dog', models.CharField(max_length=50, verbose_name='Мать')),
                ('breeder_name', models.CharField(max_length=50, verbose_name='Имя заводчика')),
                ('pedigree_of_dog_scanned_front', models.ImageField(upload_to='files/download/pedigree_of_dog', verbose_name='Паспорт фронт')),
                ('pedigree_of_dog_scanned_back', models.ImageField(upload_to='files/download/pedigree_of_dog', verbose_name='Паспорт тыл')),
                ('champion_certificate_scanned', models.ImageField(upload_to='files/download/champion_certificate', verbose_name='Сертификат чемпиона')),
                ('proof_of_peyment_scanned', models.ImageField(upload_to='files/download/proof_of_peyment', verbose_name='Оплата сбора')),
            ],
        ),
        migrations.CreateModel(
            name='Exebition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exebition', models.TextField(max_length=160, verbose_name='Тип выставки')),
                ('date_of_exebition', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('address_exebition', models.TextField(verbose_name='Место проведения')),
                ('status_of_exebition', models.IntegerField(choices=[(0, 'Close'), (1, 'Open')], default=1, verbose_name='Статус выставки')),
                ('add_classes_of_exebition', models.ManyToManyField(blank=True, to='registration_of_dogs.AdditionalCategories', verbose_name='Дополнительные категории')),
                ('participant_of_exebition', models.ManyToManyField(blank=True, to='registration_of_dogs.Dog', verbose_name='Участники выставки')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.TextField(max_length=50, verbose_name='Имя владельца')),
                ('owner_telephone', models.TextField(max_length=10, verbose_name='Телефон владельца')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Почта владельца')),
                ('status_of_user', models.BooleanField(default=False, verbose_name='Статус (зарегестрирован/без регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dog', models.CharField(max_length=50, verbose_name='Кличка')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('name_of_owner', models.CharField(max_length=50, verbose_name='Имя хозяина')),
                ('class_of_exebition', models.TextField(choices=[('1', 'YOUNGER PUPPY 3-6 months up to 35cm'), ('2', 'YOUNGER PUPPY 3-6 months over 35cm'), ('3', 'PUPPY 6-9 months to 35cm'), ('4', 'PUPPY 6-9 months over 35cm'), ('5', 'YOUNG 9-15 months up to 35cm'), ('6', 'YOUNG 9-18 months over 35cm'), ('7', 'MEDIUM 15-24 months up to 35cm'), ('8', 'MEDIUM 15-24 months over 35cm'), ('9', 'OPEN from 15 months to 35cm'), ('10', 'OPEN from 18 months over 35cm'), ('11', 'CHAMPIONS over 18 months up to 35cm - CERTIFICATE'), ('12', 'CHAMPIONS over 18 months over 35cm - CERTIFICATE'), ('13', 'VETERANS from 7 years of age up to 35cm'), ('14', 'VETERANS from 6 years of age over 35 cm'), ('15', 'WORKING from 12 months - Certificate of examination'), ('16', 'Final competitions - The most beautiful PAIR of DOGS'), ('17', 'Final competitions - The most beautiful BREEDING GROUP'), ('18', 'Final competitions - CHILD AND DOG')], verbose_name='Категория')),
                ('type_of_exebition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_exebition', to='registration_of_dogs.exebition', verbose_name='Выставка')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='name_of_owner',
            field=models.ForeignKey(help_text='Имя владельца', on_delete=django.db.models.deletion.PROTECT, related_name='name_of_owner', to='registration_of_dogs.owner'),
        ),
    ]
