# Generated by Django 3.2.7 on 2021-10-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0003_auto_20210929_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='proof_of_peyment_scanned',
        ),
        migrations.AddField(
            model_name='registrationexhibition',
            name='proof_of_peyment_scanned',
            field=models.ImageField(default=1, upload_to='files/download/proof_of_peyment', verbose_name='Оплата сбора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exebition',
            name='add_classes_of_exebition',
            field=models.ManyToManyField(blank=True, related_name='add_classes_of_exebition', to='registration_of_dogs.AdditionalCategories', verbose_name='Дополнительные категории'),
        ),
    ]
