# Generated by Django 3.2.7 on 2021-09-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0003_aboutus_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='titie',
            new_name='title',
        ),
    ]
