# Generated by Django 3.2.7 on 2021-09-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0004_rename_titie_aboutus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
