# Generated by Django 3.2.7 on 2021-10-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0005_alter_dog_champion_certificate_scanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(max_length=50, verbose_name='Имя владельца'),
        ),
    ]
