# Generated by Django 3.2.7 on 2021-09-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0006_auto_20210918_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgreePersonalData',
        ),
        migrations.DeleteModel(
            name='CategoryExebition',
        ),
        migrations.RemoveField(
            model_name='registrationexhibition',
            name='the_class',
        ),
        migrations.AddField(
            model_name='registrationexhibition',
            name='class_of_exebition',
            field=models.TextField(choices=[('YOUNGER PUPPY 3-6 months up to 35cm', 'Younger Puppy Up'), ('YOUNGER PUPPY 3-6 months over 35cm', 'Younger Puppy Ov'), ('PUPPY 6-9 months to 35cm', 'Puppy Up'), ('PUPPY 6-9 months over 35cm', 'Puppy Ov'), ('YOUNG 9-15 months up to 35cm', 'Young Yo'), ('YOUNG 9-18 months over 35cm', 'Young Ov'), ('MEDIUM 15-24 months up to 35cm', 'Medium To'), ('MEDIUM 15-24 months over 35cm', 'Medium Ov'), ('OPEN from 15 months to 35cm', 'Open To'), ('OPEN from 18 months over 35cm', 'Open Ov'), ('CHAMPIONS over 18 months up to 35cm - CERTIFICATE', 'Champions To'), ('CHAMPIONS over 18 months over 35cm - CERTIFICATE', 'Champions Ov'), ('VETERANS from 7 years of age up to 35cm', 'Veterans To'), ('VETERANS from 6 years of age over 35 cm', 'Veterans Ov'), ('WORKING from 12 months - Certificate of examination', 'Working'), ('Final competitions - The most beautiful PAIR of DOGS', 'Pair Dogs'), ('Final competitions - The most beautiful BREEDING GROUP', 'Breeding Group'), ('Final competitions - CHILD AND DOG', 'Child And Dog')], default=None, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='breed_race',
            field=models.CharField(max_length=50, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='breeder_address',
            field=models.CharField(max_length=50, verbose_name='Адрес заводчика'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='breeder_name',
            field=models.CharField(max_length=50, verbose_name='Имя заводчика'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='champion_certificate_scanned',
            field=models.FileField(upload_to='', verbose_name='Сертификат чемпиона'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='exebition_venue',
            field=models.CharField(max_length=160, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='father_of_dog',
            field=models.CharField(max_length=50, verbose_name='Отец'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='mother_of_dog',
            field=models.CharField(max_length=50, verbose_name='мать'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='name_of_dog',
            field=models.CharField(max_length=50, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='name_of_owner',
            field=models.CharField(max_length=50, verbose_name='Имя хозяина'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='owner_address',
            field=models.CharField(max_length=50, verbose_name='Адрес хозяина'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='pedigree_of_dog_scanned_back',
            field=models.FileField(upload_to='', verbose_name='Паспорт тыл'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='pedigree_of_dog_scanned_front',
            field=models.FileField(upload_to='', verbose_name='Паспорт фронт'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='proof_of_peyment_scanned',
            field=models.FileField(upload_to='', verbose_name='Оплата сбора'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='studbook_and_registration',
            field=models.CharField(max_length=50, verbose_name='Номер регистрации'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='tattoo_number_microchip',
            field=models.CharField(max_length=50, verbose_name='Номер чипа'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='type_of_exebition',
            field=models.CharField(help_text='Тип выставки', max_length=160, verbose_name='Тип выставки'),
        ),
    ]
