# Generated by Django 3.2.7 on 2021-09-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0007_auto_20210925_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexhibition',
            name='class_of_exebition',
            field=models.TextField(choices=[('1', 'YOUNGER PUPPY 3-6 months up to 35cm'), ('2', 'YOUNGER PUPPY 3-6 months over 35cm'), ('PUPPY 6-9 months to 35cm', 'Puppy Up'), ('PUPPY 6-9 months over 35cm', 'Puppy Ov'), ('YOUNG 9-15 months up to 35cm', 'Young Yo'), ('YOUNG 9-18 months over 35cm', 'Young Ov'), ('MEDIUM 15-24 months up to 35cm', 'Medium To'), ('MEDIUM 15-24 months over 35cm', 'Medium Ov'), ('OPEN from 15 months to 35cm', 'Open To'), ('OPEN from 18 months over 35cm', 'Open Ov'), ('CHAMPIONS over 18 months up to 35cm - CERTIFICATE', 'Champions To'), ('CHAMPIONS over 18 months over 35cm - CERTIFICATE', 'Champions Ov'), ('VETERANS from 7 years of age up to 35cm', 'Veterans To'), ('VETERANS from 6 years of age over 35 cm', 'Veterans Ov'), ('WORKING from 12 months - Certificate of examination', 'Working'), ('Final competitions - The most beautiful PAIR of DOGS', 'Pair Dogs'), ('Final competitions - The most beautiful BREEDING GROUP', 'Breeding Group'), ('Final competitions - CHILD AND DOG', 'Child And Dog')], verbose_name='Категория'),
        ),
    ]
