# Generated by Django 3.2.7 on 2021-10-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0007_auto_20211005_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exebition',
            name='status_of_exebition',
            field=models.IntegerField(choices=[(0, 'Close'), (1, 'Open')], default=(1, 'Open'), verbose_name='Статус выставки'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='class_of_exebition',
            field=models.TextField(choices=[('YOUNGER_PUPPY_UP', 'YOUNGER PUPPY 3-6 months up to 35cm'), ('YOUNGER_PUPPY_OV', 'YOUNGER PUPPY 3-6 months over 35cm'), ('PUPPY_UP', 'PUPPY 6-9 months to 35cm'), ('PUPPY_OV', 'PUPPY 6-9 months over 35cm'), ('YOUNG_YO', 'YOUNG 9-15 months up to 35cm'), ('YOUNG_OV', 'YOUNG 9-18 months over 35cm'), ('MEDIUM_TO', 'MEDIUM 15-24 months up to 35cm'), ('MEDIUM_OV', 'MEDIUM 15-24 months over 35cm'), ('OPEN_TO', 'OPEN from 15 months to 35cm'), ('OPEN_OV', 'OPEN from 18 months over 35cm'), ('CHAMPIONS_TO', 'CHAMPIONS over 18 months up to 35cm - CERTIFICATE'), ('CHAMPIONS_OV', 'CHAMPIONS over 18 months over 35cm - CERTIFICATE'), ('VETERANS_TO', 'VETERANS from 7 years of age up to 35cm'), ('VETERANS_OV', 'VETERANS from 6 years of age over 35 cm'), ('WORKING', 'WORKING from 12 months - Certificate of examination')], verbose_name='Категория'),
        ),
    ]
