# Generated by Django 3.2.7 on 2021-10-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0008_auto_20211024_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='status_of_user',
            field=models.BooleanField(default=False, verbose_name='Статус (зарегестрирован/без регистрации)'),
        ),
    ]
