# Generated by Django 3.2.7 on 2021-09-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0008_alter_registrationexhibition_class_of_exebition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexhibition',
            name='class_of_exebition',
            field=models.TextField(choices=[('1', 'YOUNGER PUPPY 3-6 months up to 35cm'), ('2', 'YOUNGER PUPPY 3-6 months over 35cm'), ('3', 'PUPPY 6-9 months to 35cm'), ('4', 'PUPPY 6-9 months over 35cm'), ('5', 'YOUNG 9-15 months up to 35cm'), ('6', 'YOUNG 9-18 months over 35cm'), ('7', 'MEDIUM 15-24 months up to 35cm'), ('8', 'MEDIUM 15-24 months over 35cm'), ('9', 'OPEN from 15 months to 35cm'), ('10', 'OPEN from 18 months over 35cm'), ('11', 'CHAMPIONS over 18 months up to 35cm - CERTIFICATE'), ('12', 'CHAMPIONS over 18 months over 35cm - CERTIFICATE'), ('13', 'VETERANS from 7 years of age up to 35cm'), ('14', 'VETERANS from 6 years of age over 35 cm'), ('15', 'WORKING from 12 months - Certificate of examination'), ('16', 'Final competitions - The most beautiful PAIR of DOGS'), ('17', 'Final competitions - The most beautiful BREEDING GROUP'), ('18', 'Final competitions - CHILD AND DOG')], verbose_name='Категория'),
        ),
    ]
