# Generated by Django 3.2.7 on 2021-10-24 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0009_alter_owner_status_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationexhibition',
            name='date_registration',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
    ]
