# Generated by Django 3.2.7 on 2021-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0009_alter_registrationexhibition_class_of_exebition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_exebition', models.CharField(help_text='Тип выставки', max_length=160, verbose_name='Тип выставки')),
                ('date_of_exebition', models.DateTimeField()),
                ('address_of_exebition', models.TextField()),
                ('add_classes_of_exebition', models.TextField(choices=[('15', 'WORKING from 12 months - Certificate of examination'), ('16', 'Final competitions - The most beautiful PAIR of DOGS'), ('17', 'Final competitions - The most beautiful BREEDING GROUP'), ('18', 'Final competitions - CHILD AND DOG')], verbose_name='Дополнительные категории')),
                ('status_of_exebition', models.IntegerField(choices=[(0, 'Close'), (1, 'Open')], default=1, verbose_name='Статус выставки')),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationexhibition',
            name='type_of_exebition',
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='Пол'),
        ),
    ]
