# Generated by Django 3.2.7 on 2021-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0010_auto_20210926_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexhibition',
            name='champion_certificate_scanned',
            field=models.ImageField(upload_to='files/download/champion_certificate', verbose_name='Сертификат чемпиона'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='pedigree_of_dog_scanned_back',
            field=models.ImageField(upload_to='files/download/pedigree_of_dog', verbose_name='Паспорт тыл'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='pedigree_of_dog_scanned_front',
            field=models.ImageField(upload_to='files/download/pedigree_of_dog', verbose_name='Паспорт фронт'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='proof_of_peyment_scanned',
            field=models.ImageField(upload_to='files/download/proof_of_peyment', verbose_name='Оплата сбора'),
        ),
    ]
