# Generated by Django 3.2.7 on 2021-10-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0010_registrationexhibition_date_registration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'ordering': ('published',), 'verbose_name': 'Описание', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='additionalcategories',
            options={'verbose_name': 'Дополнительные категории', 'verbose_name_plural': 'Дополнительные категории'},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'Собаку', 'verbose_name_plural': 'Собаки'},
        ),
        migrations.AlterModelOptions(
            name='exebition',
            options={'verbose_name': 'Выставка', 'verbose_name_plural': 'Выставки'},
        ),
        migrations.AlterModelOptions(
            name='fees',
            options={'verbose_name': 'Сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='registrationexhibition',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации'},
        ),
        migrations.AddField(
            model_name='registrationexhibition',
            name='proof_of_payment',
            field=models.BooleanField(default=False, verbose_name='Проверка оплаты администратором'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='champion_certificate_scanned',
            field=models.ImageField(blank=True, null=True, upload_to='media/download/champion_certificate', verbose_name='Сертификат чемпиона'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pedigree_of_dog_scanned_back',
            field=models.ImageField(upload_to='media/download/pedigree_of_dog', verbose_name='Паспорт тыл'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='pedigree_of_dog_scanned_front',
            field=models.ImageField(upload_to='media/download/pedigree_of_dog', verbose_name='Паспорт фронт'),
        ),
        migrations.AlterField(
            model_name='exebition',
            name='status_of_exebition',
            field=models.BooleanField(default=True, verbose_name='Статус выставки'),
        ),
        migrations.AlterField(
            model_name='registrationexhibition',
            name='proof_of_peyment_scanned',
            field=models.ImageField(upload_to='media/download/proof_of_peyment', verbose_name='Оплата сбора'),
        ),
    ]
