# Generated by Django 3.2.7 on 2021-09-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0013_alter_registrationexhibition_exebition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationexhibition',
            name='exebition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_of_dogs.exebitions', verbose_name='Место проведения'),
        ),
    ]
