# Generated by Django 3.2.7 on 2021-09-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_of_dogs', '0014_alter_registrationexhibition_exebition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='exebitions',
            old_name='address_of_exebition',
            new_name='address_exebition',
        ),
        migrations.RenameField(
            model_name='exebitions',
            old_name='type_of_exebition',
            new_name='type_exebition',
        ),
        migrations.RemoveField(
            model_name='registrationexhibition',
            name='exebition_type',
        ),
        migrations.AddField(
            model_name='registrationexhibition',
            name='address_of_exebition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='address_of_exebition', to='registration_of_dogs.exebitions', verbose_name='Место проведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationexhibition',
            name='type_of_exebition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_of_exebition', to='registration_of_dogs.exebitions', verbose_name='Выставка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exebitions',
            name='add_classes_of_exebition',
            field=models.TextField(verbose_name='Дополнительные категории'),
        ),
    ]
