X XXXXXXX XX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XX XXXXXX
    XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    XXXXXXX X XXXXXXXXXXXXXXXXXX X XXX XXXXX
    XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX X XXXX XXXXXXXX X XXXX XXXXX XX XXXXX 
    XXXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXX XX XXXXX XXXX XXXXXXXX XXXXX 


X XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXX
XX XXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XX XXXXXXXXX X XXXXX XXXX XXXXXXXXX X XXXXXXXXXXX
XXXXXXXXX X XXXXX X XXXXXX XXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXX XX XXX XXXXX XXX XXXXX XXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXX XXXXXXXXXXXX XXX XXXXXX XXXXX XXXXXXXX
    XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXXXXXXX XXX XXXXXXXX 
    XXX XXXXX XXXXXXXX XXXXXXX XX XXXX XXXXXXXX
    XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX
    XXX XXXXX XXXX XXXXX XXX XXXX XXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X XXXX
    
    XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXX XX XXX XXX
    XXX XXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXX X XXXXXXXXX
     
    XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXX XXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXX XX XXX XXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXX
    XXX XXXXX XXXXXX XXXXXXXXXXXXXX X XXXXX XXXXXXX
    XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX
    XXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX
    XXX XXXXX XXXXXX XXXXXXXXXXXXXX X XXXXX XXXXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXX
    XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX
    XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX XXX XXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXX XXX XXXXXX XXXXXX XX XXXXX XXXXXX XXXXX XXXXXXXXXXXX X XXXXXXXXXX XXXXXXXXXX
    
            
    
    X XXXXXXX XXXXXXXXXXXXXX XXXXXXXX XX XXX XXX X XXXXX XXXX
    X XXXXX XX XXXX XXXX XX XXX XXXXXX X XXXX XXXX XX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    X XXXXXXX XXXXXXXXXXXXXX XXXXXXXX XX XXX XXX X XXXX XXXX
    X XXXXX XX XXXX XXXX XX XXX XXXXXX X XXXX XXXX XX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    X XXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
    X XXXXX XX XXXX XXXX XX XXX XXXXXX X XXXX XXXX XX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    X XXXXXXX XXXXXXXXXXXXXX XXXXX XX XXXXXXX
    X XXXXX XX XXXX XXXX XX XXX XXXXXX X XXXX XXXX XX XXXX
    XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXXX XXXXXXXXX
    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX X XXXXXXX XXXXXX
    X X XXXXXXX XXXX X XXXX XXXXXX XXXXXXXXXX XXXX XXX XXXXXXXXXX XX XXXXXXXX XXXX XX XXXXX XXX X XXXXXX XXXX XX XXXXXXXX
    X X XXXXX XXXX XXX XXXXXXXXXX XX XXXXXXXX XXXX XXXXX XXX XXXX XXXX
    X XXXXXXX
    XXXX

X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX X XXXXX X XXXXXX XXXXXXXXXXXXXX
    X X XXXXXXX XXXX X XXXX XXXXXX XXXXXXXXXX XXXX XXX XXXXXXXXXX XX XXXXXXXX XXXX XX XXXXX XXX X XXXXXX XXXX XX XXXXXXXX
    X X XXXXX XXXX XXX XXXXXXXXXX XX XXXXXXXX XXXX XXXXX XXX XXXX XXXX
    XXXX

X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX X XXXXX X XXXXXX XXXXXXXXXXXXXX
    X     XXXXXXX XXXXX XXX XXXXXX XX XX XXXX
    X     XXXXXXX XXXXX XXX XXXXXX XXXX XXXX
    X     XXXXX XXX XXXXXX XX XXXX
    X     XXXXX XXX XXXXXX XXXX XXXX
    X     XXXXX XXXX XXXXXX XX XX XXXX
    X     XXXXX XXXX XXXXXX XXXX XXXX
    X     XXXXXX XXXXX XXXXXX XX XX XXXX
    X     XXXXXX XXXXX XXXXXX XXXX XXXX
    X     XXXX XXXX XX XXXXXX XX XXXX
    X     XXXX XXXX XX XXXXXX XXXX XXXX
    X     XXXXXXXXX XXXX XX XXXXXX XX XX XXXX X XXXXXXXXXXX
    X     XXXXXXXXX XXXX XX XXXXXX XXXX XXXX X XXXXXXXXXXX
    X     XXXXXXXX XXXX X XXXXX XX XXX XX XX XXXX
    X     XXXXXXXX XXXX X XXXXX XX XXX XXXX XX XX
    X     XXXXXXX XXXX XX XXXXXX X XXXXXXXXXXX XX XXXXXXXXXXX
    X     XXXXX XXXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXX XX XXXX
    X     XXXXX XXXXXXXXXXXX X XXX XXXX XXXXXXXXX XXXXXXXX XXXXX
    X     XXXXX XXXXXXXXXXXX X XXXXX XXX XXX

X XXXXXXXXXXXXXXXXXXX
    XXXXXXXX X XXXXXXXXXXXXXXXXXX
    XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    
    XXXXXXXXX X XXXXX XXXXXXX X XXXXXXXXXXXXX
    X XXX X XXXXXXX XXX X XX X

    X XXXXXXX XXX XXXXXXXX X XX X
    X XXXXXXX XXX XXXXX XXXXXXXXXXX X XX X
    X XXXXXXXXXXXX XX XXX XXX XX XXX XXX XX XXX XXXX X XX X XXX XXXX XXXX XXXXXXXXXX XX XXX

    X XXXXXXXXXX XXXXXXXXXXXXX

    X XXX XXXX XXXXXXXXX XXXX XX XXXX X XX X
    X XXXXXXXX XXXXX X XX X
    X XXXXX XXX XXX X XXXX XX XXXXXXX
    X XXXXXXXXXXXX XXXXXXXX XX XXXX XXXXXX XXX XXXXX XX XXX XXXXXXXXXX
    X XXXX XXX X XXXXXXXX XXXXXXXXXXX XXX XXXX XXXX XXXXXX X XXXXXXXXX XX XXX XXXXX XXXXXXXX XX XXX XXXXXXXXXXXX
    X XXXXXX X XXXXXXXXX XX XXX XXXXXXX XX XXXXX XXXX XX XXX XXXXXXXXXXXX
    X XXXXX XX XXX XXXXXXX XXXX XX XXXXXXXXXXX XX X XXX XX XX XXXXX X XXXXXX X XXX
    X XXXXXXXXXXXXX XXX XX XXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
    
